StarBlog/StarBlog.Web/ViewModels/HomeViewModel.cs
using StarBlog.Data.Models;

namespace StarBlog.Web.ViewModels;

public class HomeViewModel {
    /// <summary>
    /// 随机图片
    /// </summary>
    public Photo? RandomPhoto { get; set; }

    /// <summary>
    /// 是否显示 Chart
    /// </summary>
    public bool ChartVisible { get; set; } = true;

    /// <summary>
    /// 是否显示随机图片
    /// </summary>
    public bool RandomPhotoVisible { get; set; } = false;

    /// <summary>
    /// 置顶博客
    /// </summary>
    public Post? TopPost { get; set; }

    /// <summary>
    /// 推荐博客
    /// </summary>
    public List<Post> FeaturedPosts { get; set; } = new();

    /// <summary>
    /// 推荐照片，原则上只能三个
    /// </summary>
    public List<Photo> FeaturedPhotos { get; set; } = new();

    /// <summary>
    /// 推荐分类，原则上三个
    /// </summary>
    public List<FeaturedCategory> FeaturedCategories { get; set; } = new();

    /// <summary>
    /// 友情链接
    /// </summary>
    public List<Link> Links { get; set; } = new();

    /// <summary>
    /// 一句诗
    /// </summary>
    public string OnePoem { get; set; }

    /// <summary>
    /// 一言
    /// </summary>
    public string Hitokoto { get; set; }
}

StarBlog/StarBlog.Web/ViewModels/InitViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StarBlog.Web.ViewModels;

public class InitViewModel {
    [Display(Name = "用户名")]
    public string Username { get; set; }

    [Display(Name = "密码")]
    public string Password { get; set; }

    [Display(Name = "博客域名")]
    public string Host { get; set; }

    [Display(Name = "文章默认渲染方式")]
    public string DefaultRender { get; set; }
}

StarBlog/StarBlog.Web/Controllers/BlogController.cs
using FreeSql;
using Microsoft.AspNetCore.Mvc;
using StarBlog.Data.Models;
using StarBlog.Web.Contrib.SiteMessage;
using StarBlog.Web.Services;
using StarBlog.Web.ViewModels.Blog;
using StarBlog.Web.ViewModels.QueryFilters;
using X.PagedList;

namespace StarBlog.Web.Controllers;

[ApiExplorerSettings(IgnoreApi = true)]
public class BlogController : Controller {
    private readonly MessageService _messages;
    private readonly IBaseRepository<Post> _postRepo;
    private readonly IBaseRepository<Category> _categoryRepo;
    private readonly PostService _postService;
    private readonly CategoryService _categoryService;
    private readonly ConfigService _configService;

    public BlogController(IBaseRepository<Post> postRepo,
        IBaseRepository<Category> categoryRepo,
        PostService postService,
        MessageService messages,
        CategoryService categoryService,
        ConfigService configService) {
        _postRepo = postRepo;
        _categoryRepo = categoryRepo;
        _postService = postService;
        _messages = messages;
        _categoryService = categoryService;
        _configService = configService;
    }

    public async Task<IActionResult> List(int categoryId = 0, int page = 1, int pageSize = 6,
        string sortType = "asc", string sortBy = "-CreationTime") {
        var currentCategory = categoryId == 0
            ? new Category { Id = 0, Name = "All" }
            : await _categoryRepo.Where(a => a.Id == categoryId).FirstAsync();

        if (currentCategory == null) {
            _messages.Error($"分类 {categoryId} 不存在！");
            return RedirectToAction(nameof(List));
        }

        if (!currentCategory.Visible) {
            _messages.Warning($"分类 {categoryId} 暂不开放！");
            return RedirectToAction(nameof(List));
        }

        return View(new BlogListViewModel {
            CurrentCategory = currentCategory,
            CurrentCategoryId = categoryId,
            CategoryNodes = await _categoryService.GetNodes(),
            SortType = sortType,
            SortBy = sortBy,
            Posts = await _postService.GetPagedList(new PostQueryParameters {
                CategoryId = categoryId,
                Page = page,
                PageSize = pageSize,
                OnlyPublished = true,
                SortBy = sortType == "desc" ? $"-{sortBy}" : sortBy
            })
        });
    }

    [Route("/p/{slug}")]
    public async Task<IActionResult> PostBySlug(string slug) {
        var p = await _postRepo.Where(a => a.Slug == slug).FirstAsync();
        return await Post(p?.Id ?? "");
    }

    public async Task<IActionResult> Post(string id) {
        var post = await _postService.GetById(id);

        if (post == null) {
            _messages.Error($"文章 {id} 不存在！");
            return RedirectToAction(nameof(List));
        }

        if (!post.IsPublish) {
            _messages.Warning($"文章 {id} 未发布！");
            return RedirectToAction(nameof(List));
        }

        var viewName = "Post.FrontendRender";
        if (_configService["default_render"] == "backend") {
            viewName = "Post.BackendRender";
        }

        return View(viewName, await _postService.GetPostViewModel(post));
    }

    public IActionResult RandomPost() {
        var posts = _postRepo.Where(a => a.IsPublish).ToList();
        if (posts.Count == 0) {
            _messages.Error("当前没有文章，请先添加文章！");
            return RedirectToAction("Index", "Home");
        }

        var rndPost = posts[Random.Shared.Next(posts.Count)];
        _messages.Info($"随机推荐了文章 <b>{rndPost.Title}</b> 给你~" +
                       $"<span class='ps-3'><a href=\"{Url.Action(nameof(RandomPost))}\">再来一次</a></span>");
        return RedirectToAction(nameof(Post), new { id = rndPost.Id });
    }

    public IActionResult Temp() {
        return View();
    }
}

StarBlog/StarBlog.Web/Controllers/HomeController.cs
using FreeSql;
using Microsoft.AspNetCore.Mvc;
using StarBlog.Data.Models;
using StarBlog.Share.Extensions;
using StarBlog.Web.Contrib.SiteMessage;
using StarBlog.Web.Extensions;
using StarBlog.Web.Services;
using StarBlog.Web.ViewModels;

namespace StarBlog.Web.Controllers;

public class HomeController : Controller {
    private readonly BlogService _blogService;
    private readonly PhotoService _photoService;
    private readonly CategoryService _categoryService;
    private readonly LinkService _linkService;
    private readonly MessageService _messages;
    private readonly ConfigService _conf;

    public HomeController(BlogService blogService, PhotoService photoService, CategoryService categoryService,
        LinkService linkService,
        MessageService messages, ConfigService conf) {
        _blogService = blogService;
        _photoService = photoService;
        _categoryService = categoryService;
        _linkService = linkService;
        _messages = messages;
        _conf = conf;
    }

    public async Task<IActionResult> Index() {
        if (Request.QueryString.HasValue) {
            return BadRequest();
        }

        var vm = new HomeViewModel {
            ChartVisible = _conf["home_chart_visible"] == "true",
            RandomPhotoVisible = _conf["home_random_photo_visible"] == "true",
            RandomPhoto = await _photoService.GetRandomPhoto(),
            TopPost = await _blogService.GetTopOnePost(),
            FeaturedPosts = await _blogService.GetFeaturedPosts(),
            FeaturedPhotos = await _photoService.GetFeaturedPhotos(),
            FeaturedCategories = await _categoryService.GetFeaturedCategories(),
            Links = await _linkService.GetAll()
        };

        if (HttpContext.Request.IsMobileBrowser()) {
            vm.ChartVisible = false;
            vm.RandomPhotoVisible = false;
        }

        return View(vm);
    }

    [HttpGet]
    public IActionResult Init([FromServices] ConfigService conf) {
        if (conf["is_init"] == "true") {
            _messages.Error("已经完成初始化！");
            return RedirectToAction(nameof(Index));
        }

        return View(new InitViewModel {
            Host = conf["host"],
            DefaultRender = conf["default_render"]
        });
    }

    [HttpPost]
    public IActionResult Init([FromServices] IBaseRepository<User> userRepo, InitViewModel vm) {
        if (_conf["is_init"] == "true") {
            _messages.Error("已经完成初始化！");
            return RedirectToAction(nameof(Index));
        }

        if (!ModelState.IsValid) return View();

        // 保存配置
        _conf["host"] = vm.Host;
        _conf["default_render"] = vm.DefaultRender;
        _conf["is_init"] = "true";

        // 创建用户
        // to do 这里暂时存储明文密码，后期要换成MD5加密存储。2023-5-7 搞定
        // todo 使用加盐的hash密码 https://www.ais.com/how-to-generate-a-jwt-token-using-net-6/
        userRepo.Insert(new User {
            Id = Guid.NewGuid().ToString(),
            Name = vm.Username,
            Password = vm.Password.ToSHA256()
        });

        _messages.Success("初始化完成！");
        return RedirectToAction(nameof(Index));
    }
}

StarBlog/StarBlog.Web/Controllers/LinkExchangeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using StarBlog.Data.Models;
using StarBlog.Web.Contrib.SiteMessage;
using StarBlog.Web.Services;
using StarBlog.Web.ViewModels.LinkExchange;

namespace StarBlog.Web.Controllers;

public class LinkExchangeController : Controller {
    private readonly ILogger<LinkExchangeController> _logger;
    private readonly LinkExchangeService _service;
    private readonly IMapper _mapper;
    private readonly MessageService _messages;

    public LinkExchangeController(ILogger<LinkExchangeController> logger, LinkExchangeService service, IMapper mapper,
        MessageService messages) {
        _logger = logger;
        _service = service;
        _mapper = mapper;
        _messages = messages;
    }

    [HttpGet]
    public IActionResult Add() {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(LinkExchangeAddViewModel vm) {
        if (!ModelState.IsValid) return View();

        if (await _service.HasUrl(vm.Url)) {
            _messages.Error("相同网址的友链申请已提交！");
            return View();
        }

        var item = _mapper.Map<LinkExchange>(vm);
        item = await _service.AddOrUpdate(item);

        // 发送邮件通知
        await _service.SendEmailOnAdd(item);

        _messages.Info("友链申请已提交，正在处理中，请及时关注邮件通知~");
        return RedirectToAction("Index", "Home");
    }
}

StarBlog/StarBlog.Web/Controllers/PhotographyController.cs
using Microsoft.AspNetCore.Mvc;
using StarBlog.Web.Contrib.SiteMessage;
using StarBlog.Web.Services;
using StarBlog.Web.ViewModels.Photography;

namespace StarBlog.Web.Controllers;

public class PhotographyController : Controller {
    private readonly PhotoService _photoService;
    private readonly MessageService _messages;

    public PhotographyController(PhotoService photoService, MessageService messages) {
        _photoService = photoService;
        _messages = messages;
    }

    public async Task<IActionResult> Index(int page = 1, int pageSize = 10) {
        return View(new PhotographyViewModel {
            Photos = await _photoService.GetPagedList(page, pageSize)
        });
    }

    public async Task<IActionResult> Photo(string id) {
        var photo = await _photoService.GetById(id);
        if (photo == null) {
            _messages.Error($"图片 {id} 不存在！");
            return RedirectToAction(nameof(Index));
        }

        return View(photo);
    }

    public async Task<IActionResult> Next(string id) {
        var item = await _photoService.GetNext(id);
        if (item == null) {
            _messages.Warning("没有下一张图片了~");
            return RedirectToAction(nameof(Photo), new {id});
        }

        return RedirectToAction(nameof(Photo), new {id = item.Id});
    }

    public async Task<IActionResult> Previous(string id) {
        var item = await _photoService.GetPrevious(id);
        if (item == null) {
            _messages.Warning("没有上一张图片了~");
            return RedirectToAction(nameof(Photo), new {id});
        }

        return RedirectToAction(nameof(Photo), new {id = item.Id});
    }

    public async Task<IActionResult> RandomPhoto() {
        var item = await _photoService.GetRandomPhoto();
        if (item == null) {
            _messages.Error("当前没有图片，请先上传！");
            return RedirectToAction("Index", "Home");
        }

        _messages.Info($"随机推荐了图片 <b>{item.Title}</b> 给你~" +
                       $"<span class='ps-3'><a href=\"{Url.Action(nameof(RandomPhoto))}\">再来一次</a></span>");
        return RedirectToAction(nameof(Photo), new {id = item.Id});
    }
}

StarBlog/StarBlog.Web/Views/Home/Index.cshtml
@using StarBlog.Share.Extensions
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="container col-xxl-8 py-3">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div class="col-10 col-sm-8 col-lg-6">
            @if (Model.RandomPhotoVisible) {
                @if (Model.RandomPhoto != null) {
                    <partial name="Widgets/PhotoCardSmallPure" model="@Model.RandomPhoto"/>
                }
                else {
                    <img src="~/images/bootstrap/bootstrap-themes.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes"
                         width="700" height="500" loading="lazy">
                }
            }
            @if (Model.ChartVisible) {
                <canvas class="my-4 w-100" id="myChart" height="400"></canvas>
            }
        </div>
        <div class="col-lg-6">
            <h1 class="display-5 fw-bold lh-1 mb-3">DealiAxy's Blog</h1>
            <div class="lead">
                <p>一句诗：{{poemSimple}}</p>
                <p>一言：{{hitokoto}}</p>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                <a class="btn btn-primary btn-lg px-4" asp-controller="Blog" asp-action="RandomPost">看文</a>
                <a class="btn btn-outline-secondary btn-lg px-4" asp-controller="Photography" asp-action="RandomPhoto">看图</a>
                @if (Model.ChartVisible) {
                    <button class="btn btn-outline-secondary btn-lg px-4" @@click="switchChartType">切换图表</button>
                }
            </div>
        </div>
    </div>
</div>

<div class="container px-4 py-3" id="custom-cards">
    <h2 class="pb-2 border-bottom">Photography</h2>

    @if (Model.FeaturedPhotos.Any()) {
        <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
            @foreach (var photo in Model.FeaturedPhotos) {
                <div class="col">
                    <partial name="Widgets/PhotoCardSmall" model="photo"/>
                </div>
            }
        </div>
    }
    else {
        @await Html.PartialAsync("Widgets/PlaceholderCard", "推荐图片")
    }

</div>

<div class="container px-4 py-3" id="featured-3">
    <h2 class="pb-2 border-bottom">Blog Categories</h2>
    @if (Model.FeaturedCategories.Any()) {
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
            @foreach (var fc in Model.FeaturedCategories) {
                @await Html.PartialAsync("Widgets/FeaturedCategoryCard", fc)
            }
        </div>
    }
    else {
        @await Html.PartialAsync("Widgets/PlaceholderCard", "推荐分类")
    }

</div>

<div class="container px-4 py-3">
    <h2 class="pb-2 border-bottom">Blog Posts</h2>

    @if (Model.TopPost != null) {
        <partial name="Widgets/TopPostCard" model="Model.TopPost"/>
    }
    else {
        @await Html.PartialAsync("Widgets/PlaceholderCard", "置顶博客")
    }


    @if (Model.FeaturedPosts.Any()) {
        <div class="row mb-2">
            @foreach (var post in @Model.FeaturedPosts) {
                <partial name="Widgets/FeaturedPostCard" model="post"/>
            }
        </div>
    }
    else {
        @await Html.PartialAsync("Widgets/PlaceholderCard", "推荐博客")
    }
</div>

<div class="container px-4 py-3">
    <div class="d-flex justify-content-between mb-2 border-bottom">
        <h2>友情链接</h2>
        <a class="btn btn-link" asp-controller="LinkExchange" asp-action="Add">申请友链</a>
    </div>
    @if (Model.Links.Any()) {
        <div class="d-grid gap-2 d-md-block">
            @foreach (var link in Model.Links) {
                @await Html.PartialAsync("Widgets/ColorfulButton",
                           new ColorfulButtonViewModel {Name = link.Name, Url = link.Url, Tooltips = link.Description})
            }
        </div>
    }
    else {
        @await Html.PartialAsync("Widgets/PlaceholderCard", "友情链接")
    }
</div>

@section bottom {
    <script src="~/lib/chart.js/dist/chart.min.js"></script>
    @if (Model.ChartVisible) {
        <script>const CHART_VISIBLE = true</script>
    }
    else {
        <script>const CHART_VISIBLE = false</script>
    }
    <script type="module" src="~/js/home.js"></script>
}

StarBlog/StarBlog.Web/Views/Home/Init.cshtml
@model InitViewModel
@{
    ViewData["Title"] = "Init";
}

<div class="container px-4 py-3">
    <h2 class="d-flex w-100 justify-content-between pb-2 mb-3 border-bottom">
        <div>Blog Init</div>
        <div>系统初始化</div>
    </h2>

    <div class="card px-1">
        <form enctype="multipart/form-data" class="card-body row" asp-controller="Home" asp-action="Init" method="post">
            <div class="text-danger" asp-validation-summary="All"></div>

            <div class="col-xl-6 py-3">
                <h5 class="card-title">创建管理员账号</h5>
                <h6 class="card-subtitle mb-3 text-muted">用于登录管理后台</h6>
                <div class="mb-3">
                    <label asp-for="Username" class="form-label"></label>
                    <input asp-for="Username" class="form-control" aria-describedby="usernameHelp">
                    <div class="form-text">设置个用户名给管理员用</div>
                </div>
                <div class="mb-3">
                    <label asp-for="Password" class="form-label"></label>
                    <input asp-for="Password" class="form-control" aria-describedby="passwordHelp">
                    <div class="form-text">得有密码才能登录</div>
                </div>
            </div>

            <div class="col-xl-6 py-3">
                <h5 class="card-title">系统配置</h5>
                <h6 class="card-subtitle mb-3 text-muted">一些初始化的配置</h6>
                <div class="mb-3">
                    <label asp-for="Host" class="form-label"></label>
                    <input asp-for="Host" class="form-control" aria-describedby="hostHelp">
                    <div class="form-text">设置链接前缀，之后可以在管理后台修改</div>
                </div>
                <div class="mb-3">
                    <label asp-for="DefaultRender" class="form-label"></label>
                    <select asp-for="DefaultRender" class="form-select">
                        <option value="frontend" selected>前端渲染</option>
                        <option value="backend">后端渲染（Alpha）</option>
                    </select>
                    <span asp-validation-for="DefaultRender" class="form-text text-danger"></span>
                    <div class="form-text">
                        设置博客文章的渲染方式，前端渲染使用Editor.md实现，后端渲染一致性更好。<br>
                        具体区别可以查看<a href="https://www.cnblogs.com/deali/p/16834452.html" target="_blank">这篇文章</a>。
                        设置之后可以在管理后台修改
                    </div>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">提交</button>
                <button type="reset" class="btn btn-outline-warning">重置</button>
            </div>
        </form>
    </div>


</div>