StarBlog/StarBlog.Web/ViewModels/BackToTopViewModel.cs
namespace StarBlog.Web.ViewModels; 

public class BackToTopViewModel {
    public bool IsShowText { get; set; } = true;
}

StarBlog/StarBlog.Web/ViewModels/ColorfulButtonViewModel.cs
namespace StarBlog.Web.ViewModels;

public static class LinkTarget {
    public const string Blank = "_blank";
    public const string Parent = "_parent";
    public const string Self = "_self";
    public const string Top = "_top";
}

public class ColorfulButtonViewModel {
    public string Name { get; set; }
    public string Url { get; set; } = "#";
    public string Target { get; set; } = LinkTarget.Blank;
    public string? Tooltips { get; set; }
}

StarBlog/StarBlog.Web/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace StarBlog.Web.Controllers; 

public class AboutController : Controller {
    // GET
    public IActionResult Index() {
        return View();
    }
}

StarBlog/StarBlog.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace StarBlog.Web.Controllers; 

public class ProductController : Controller {
    public IActionResult Index() {
        return View();
    }
}

StarBlog/StarBlog.Web/Controllers/RssController.cs
using System.ServiceModel.Syndication;
using System.Text;
using System.Xml;
using FreeSql;
using Microsoft.AspNetCore.Mvc;
using StarBlog.Data.Models;
using StarBlog.Web.Services;

namespace StarBlog.Web.Controllers;

[ApiExplorerSettings(IgnoreApi = true)]
public class RssController : Controller {
    private readonly IBaseRepository<Post> _postRepo;
    private readonly ConfigService _conf;

    public RssController(IBaseRepository<Post> postRepo, ConfigService conf) {
        _postRepo = postRepo;
        _conf = conf;
    }

    [HttpGet]
    public IActionResult Index() {
        var feedUrl = Path.Combine(_conf["host"], "feed");
        ViewBag.FeedUrl = feedUrl;
        return View();
    }

    [ResponseCache(Duration = 1200)]
    [HttpGet("feed")]
    public async Task<IActionResult> Feed() {
        var posts = await _postRepo.Where(a => a.IsPublish && a.CreationTime.Year == DateTime.Now.Year)
            .OrderByDescending(a => a.LastUpdateTime)
            .Include(a => a.Category)
            .ToListAsync();

        var feed = new SyndicationFeed(
            "StarBlog",
            "「程序设计实验室」 专注于互联网热门新技术探索与团队敏捷开发实践，包括架构设计、机器学习与数据分析算法、移动端开发、Linux、Web前后端开发等，欢迎一起探讨技术，分享学习实践经验。",
            new Uri("http://blog.deali.cn"), "RSSUrl", posts.First().LastUpdateTime
        ) {
            Copyright = new TextSyndicationContent($"{DateTime.Now.Year} DealiAxy")
        };

        var items = new List<SyndicationItem>();
        foreach (var item in posts) {
            var postUrl = Url.Action("Post", "Blog", new {id = item.Id}, HttpContext.Request.Scheme);
            items.Add(new SyndicationItem(item.Title,
                new TextSyndicationContent(PostService.GetContentHtml(item), TextSyndicationContentKind.Html),
                new Uri(postUrl), item.Id, item.LastUpdateTime
            ) {
                Categories = {new SyndicationCategory(item.Category?.Name)},
                Authors = {new SyndicationPerson("admin@deali.cn", "DealiAxy", "https://deali.cn")},
                PublishDate = item.CreationTime,
                Summary = new TextSyndicationContent(item.Summary)
            });
        }

        feed.Items = items;

        var settings = new XmlWriterSettings {
            Async = true,
            Encoding = Encoding.UTF8,
            NewLineHandling = NewLineHandling.Entitize,
            NewLineOnAttributes = true,
            Indent = true
        };
        using var stream = new MemoryStream();
        await using var xmlWriter = XmlWriter.Create(stream, settings);
        var rssFormatter = new Atom10FeedFormatter(feed);
        rssFormatter.WriteTo(xmlWriter);
        await xmlWriter.FlushAsync();

        return File(stream.ToArray(), "application/xml; charset=utf-8");
    }
}

StarBlog/StarBlog.Web/Controllers/SearchController.cs
using FreeSql;
using Microsoft.AspNetCore.Mvc;
using StarBlog.Data.Models;
using StarBlog.Web.ViewModels;

namespace StarBlog.Web.Controllers;

public class SearchController : Controller {
    private readonly IBaseRepository<Post> _postRepo;
    private readonly IBaseRepository<Category> _categoryRepo;

    public SearchController(IBaseRepository<Post> postRepo, IBaseRepository<Category> categoryRepo) {
        _postRepo = postRepo;
        _categoryRepo = categoryRepo;
    }

    public IActionResult Blog(string keyword, int categoryId = 0, int page = 1, int pageSize = 5) {
        var posts = _postRepo
            .Where(a => a.IsPublish)
            .Where(a => a.Title!.Contains(keyword))
            .Include(a => a.Category)
            .ToList();

        return View("Result", new SearchResultViewModel {
            Keyword = keyword,
            Posts = posts
        });
    }
}

StarBlog/StarBlog.Web/Views/Shared/Widgets/Alert.cshtml
@using StarBlog.Web.Contrib.SiteMessage
@model Message?

@if (Model != null) {
    <div class="alert alert-@Model.Tag d-flex align-items-center alert-dismissible fade show" role="alert">
        <div class="mx-2" style="font-size: 2rem">
            @switch (Model.Tag) {
                case MessageTags.Debug:
                    <i class="fa fa-question-circle me-2"></i>
                    break;
                case MessageTags.Info:
                    <i class="fa fa-info-circle me-2"></i>
                    break;
                case MessageTags.Success:
                    <i class="fa fa-check-circle me-2"></i>
                    break;
                case MessageTags.Warning:
                    <i class="fa fa-exclamation-triangle me-2"></i>
                    break;
                case MessageTags.Error:
                    <i class="fa fa-times-circle me-2"></i>
                    break;
            }
        </div>
        
        <div>
            @if (Model.Title != null) {
                <h5>@Html.Raw(Model.Title)</h5>
            }
            @Html.Raw(Model.Content)
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
}

StarBlog/StarBlog.Web/Views/Shared/Widgets/BackToTop.cshtml
@model BackToTopViewModel

<div class="position-fixed top-0 end-0 p-3" style="z-index: 11">
    <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <img src="~/images/codelab.jpg" class="rounded me-2" alt="..." style="width: 20px;height: 20px;">
            <strong class="me-auto">程序设计实验室</strong>
            <small>微信公众号</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
            <div class="card border-0">
                <img src="~/images/qrcode_sm.jpg" alt="qrcode" class="card-img-top">
                <div class="card-body">
                    <h6 class="card-title">一个技术探索与知识分享的平台~</h6>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="btn-group-vertical position-fixed bottom-0 end-0 me-3 mb-3" role="group" aria-label="右下角工具" style="z-index: 11">
    <button type="button" class="btn btn-success" id="liveToastBtn">
        <i class="fa-brands fa-weixin"></i>
        @if (Model.IsShowText) {
            <span>微信公众号</span>
        }
    </button>
    <a class="btn btn-primary" href="#" role="button">
        <i class="fa-solid fa-arrow-up"></i>
        @if (Model.IsShowText) {
            <span>返回顶部</span>
        }
    </a>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/ColorfulButton.cshtml
@model ColorfulButtonViewModel

@{
    var rnd = Random.Shared;
    var colorList = new[] {
        "btn-outline-primary",
        "btn-outline-secondary",
        "btn-outline-success",
        "btn-outline-danger",
        "btn-outline-warning",
        "btn-outline-info",
        "btn-outline-dark",
    };
    var btnColor = colorList[rnd.Next(0, colorList.Length)];
}

<a href="@Model.Url" role="button" class="btn btn-sm @btnColor mb-1" target="@Model.Target"
   data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="@Model.Tooltips">
    @Model.Name
</a>

StarBlog/StarBlog.Web/Views/Shared/Widgets/FeaturedCategoryCard.cshtml
@model FeaturedCategory

<div class="feature col">
    <div class="feature-icon bg-primary bg-gradient">
        <div class="bi">
            <i class="@Model.IconCssClass"></i>
        </div>
    </div>
    <h2>@Model.Name</h2>
    <p>@Model.Description</p>
    <a class="icon-link" asp-controller="Blog" asp-action="List" asp-route-categoryId="@Model.CategoryId.ToString()">
        More posts
        <span class="bi">
            <i class="fa-solid fa-chevron-right"></i>
        </span>
    </a>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/FeaturedPostCard.cshtml
@using StarBlog.Share.Extensions
@model Post

<div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary">@Model.Category.Name</strong>
            <h5 class="mb-0">@Model.Title</h5>
            <div class="mb-1 text-muted">@Model.LastUpdateTime.ToShortDateString()</div>
            <p class="card-text mb-auto">@Model.Summary.Limit(50)</p>
            <a class="stretched-link"
               asp-controller="Blog" asp-action="Post" asp-route-id="@Model.Id">
                Continue reading
            </a>
        </div>
        <div class="col-auto d-none d-lg-block">
            <img class="bd-placeholder-img" alt=""
                 src="@Url.Action("GetRandomImage", "PicLib", new { Seed = Model.Id, Width = 200, Height = 250 })">
        </div>
    </div>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/Header1.cshtml
<header id="vue-header">
    <div class="px-3 py-2 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none"
                   asp-controller="Home" asp-action="Index">
                    <img src="~/images/codelab.jpg" class="rounded-circle" alt="" style="height: 64px;width: 64px;">
                </a>

                <ul class="nav col-12 col-lg-auto pt-1 my-2 justify-content-center my-md-0 text-small">
                    <li>
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">
                            <div class="bi d-block mx-auto mb-1 text-center">
                                <i class="fa-solid fa-house fa-2xl"></i>
                            </div>
                            Home
                        </a>
                    </li>
                    <li>
                        <a class="nav-link text-white" asp-controller="Blog" asp-action="List">
                            <div class="bi d-block mx-auto mb-1 text-center">
                                <i class="fa-solid fa-table-list fa-2xl"></i>
                            </div>
                            Blog
                        </a>
                    </li>
                    <li>
                        <a class="nav-link text-white" asp-controller="Photography" asp-action="Index">
                            <div class="bi d-block mx-auto mb-1 text-center">
                                <i class="fa-solid fa-images fa-2xl"></i>
                            </div>
                            Photos
                        </a>
                    </li>
                    @* <li> *@
                    @*     <a class="nav-link text-white" asp-controller="Product" asp-action="Index"> *@
                    @*         <div class="bi d-block mx-auto mb-1 text-center"> *@
                    @*             <i class="fa-solid fa-cubes fa-2xl"></i> *@
                    @*         </div> *@
                    @*         Products *@
                    @*     </a> *@
                    @* </li> *@
                    @* <li> *@
                    @*     <a href="#" class="nav-link text-white"> *@
                    @*         <div class="bi d-block mx-auto mb-1 text-center"> *@
                    @*             <i class="fa-solid fa-terminal fa-2xl"></i> *@
                    @*         </div> *@
                    @*         Console *@
                    @*     </a> *@
                    @* </li> *@
                    <li>
                        <a class="nav-link text-white" asp-controller="Rss" asp-action="Index">
                            <div class="bi d-block mx-auto mb-1 text-center">
                                <i class="fa-solid fa-rss fa-2xl"></i>
                            </div>
                            RSS
                        </a>
                    </li>
                    <li>
                        <a class="nav-link text-white" asp-controller="About" asp-action="Index">
                            <div class="bi d-block mx-auto mb-1 text-center">
                                <i class="fa-solid fa-circle-info fa-2xl"></i>
                            </div>
                            About
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
        <div class="container d-flex flex-wrap justify-content-center">
            <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto"
                  asp-controller="Search" asp-action="Blog" method="get">
                <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name="keyword">
            </form>

            <div class="text-end">
                <span class="dropdown me-2">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        Themes
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li v-for="theme in themes">
                            <a v-if="theme.name===currentTheme" class="dropdown-item active">{{theme.name}}</a>
                            <a v-else class="dropdown-item" v-on:click="setTheme(theme.name)">{{theme.name}}</a>
                        </li>
                    </ul>
                </span>
                @* todo 登录注册功能后续再来 *@
                @* <button type="button" class="btn btn-light text-dark me-2">Login</button> *@
                @* <button type="button" class="btn btn-primary">Sign-up</button> *@
            </div>
        </div>
    </div>
</header>

StarBlog/StarBlog.Web/Views/Shared/Widgets/Header2.cshtml
@using StarBlog.Web.Utils
<nav class="navbar navbar-expand-md navbar-dark bg-dark" id="vue-header">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="~/images/codelab.jpg" class="rounded-circle" alt="" style="height: 40px;width: 40px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link @ViewContext.NavItemActive("Home", "Index")"
                       asp-controller="Home" asp-action="Index">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @ViewContext.NavItemActive("Blog", "List")"
                       asp-controller="Blog" asp-action="List">
                        Blog
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @ViewContext.NavItemActive("Photography", "Index")" 
                       asp-controller="Photography" asp-action="Index">
                        Photography
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @ViewContext.NavItemActive("Rss", "Index")"
                       asp-controller="Rss" asp-action="Index">
                        Rss
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @ViewContext.NavItemActive("About", "Index")"
                       asp-controller="About" asp-action="Index">
                        About
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false">Themes</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown04">
                        <li v-for="theme in themes">
                            <a v-if="theme.name===currentTheme" class="dropdown-item active">{{theme.name}}</a>
                            <a v-else class="dropdown-item" v-on:click="setTheme(theme.name)">{{theme.name}}</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <form asp-controller="Search" asp-action="Blog" method="get">
                <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name="keyword">
            </form>
        </div>
    </div>
</nav>

StarBlog/StarBlog.Web/Views/Shared/Widgets/NoPostCard.cshtml
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-10">
            <div class="card-body">
                <h5 class="card-title">当前分类没有文章</h5>
                <div class="card-text text-muted">
                    <small>不了吧，这个分类还没写文章呢~</small>
                </div>
                <p class="card-text">要不扫码关注公众号看看有什么有趣的？</p>
                <a class="btn btn-outline-secondary stretched-link" href="#">
                    催更！
                </a>
            </div>
        </div>
        <div class="col-md-2">
            <img src="~/images/qrcode_sm.jpg" class="img-fluid rounded-start" width="200" alt="">
        </div>
    </div>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/PhotoCard.cshtml
@using StarBlog.Share.Extensions
@model Photo
@{
    // var imageSrc = @Url.Action("GetThumb", "Photo", new {id = Model.Id, width = 300});
    var imageSrc = "media/photography/" + Model.FilePath.Replace("\\", "/") + "?width=300";
}

<div class="card">
    <img class="bd-placeholder-img card-img-top" alt="@Model.Title" src="@imageSrc">

    <div class="card-body">
        <h5 class="card-title">
            <a class="stretched-link" asp-controller="Photography" asp-action="Photo" asp-route-id="@Model.Id">
                @Model.Title.Limit(8)
            </a>
        </h5>
        <div class="card-text d-flex justify-content-between small">
            <span>@Model.Location.Limit(8)</span>
            <span>
                @Model.CreateTime.ToShortDateString()
                @Model.CreateTime.ToShortTimeString()
            </span>
        </div>
    </div>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/PhotoCardSmall.cshtml
@using StarBlog.Share.Extensions
@model Photo

<div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
     style="background-image: url('media/photography/@Model.FilePath.Replace("\\", "/")?width=300');">
    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
        <h2 class="pt-5 mt-5 mb-5 display-6 lh-1 fw-bold">
            @Model.Title.Limit(8)
            <p></p>
        </h2>
        <ul class="d-flex list-unstyled mt-auto">
            <li class="me-auto">
                <img src="~/images/star.jpg" alt="Bootstrap" width="32" height="32" class="rounded-circle border border-white">
            </li>
            <li class="d-flex align-items-center me-3">
                <span class="bi me-2">
                    <i class="fa-solid fa-location-pin"></i>
                </span>
                <small>@Model.Location.Limit(8)</small>
            </li>
            <li class="d-flex align-items-center">
                <span class="bi me-2">
                    <i class="fa-solid fa-calendar-days"></i>
                </span>
                <small>@Model.CreateTime.ToShortDateString()</small>
            </li>
        </ul>
    </div>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/PhotoCardSmallPure.cshtml
@model Photo

<div class="card card-cover overflow-hidden shadow-lg rounded-2"
     style="background-image: url('media/photography/@Model.FilePath.Replace("\\", "/")?width=300'); height:20em;">

</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/PlaceholderCard.cshtml
@model string

<div class="card mb-2">
    <div class="card-header">@Model</div>
    <div class="card-body">
        <h3>虚位以待~</h3>
    </div>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/PostCard.cshtml
@model Post

<div class="card mb-3">
    <div class="card-header">
        @Model.Category.Name
    </div>
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text">
            @Model.Summary
        </p>
        @if (!string.IsNullOrWhiteSpace(Model.Slug)) {
            <a class="btn btn-outline-secondary stretched-link" href="/p/@Model.Slug">
                查看全文
            </a>
        }
        else {
            <a class="btn btn-outline-secondary stretched-link"
               asp-controller="Blog" asp-action="Post" asp-route-id="@Model.Id">
                查看全文
            </a>   
        }
    </div>
</div>

StarBlog/StarBlog.Web/Views/Shared/Widgets/TopPostCard.cshtml
@model Post

<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <div class="display-6 fst-italic">@Model.Title</div>
        <p class="lead my-3">@Model.Summary</p>
        <p class="lead mb-0">
            <a class="text-white fw-bold"
               asp-controller="Blog" asp-action="Post" asp-route-id="@Model.Id">
                Continue reading...
            </a>
        </p>
    </div>
</div>